# Generated by Django 3.2.8 on 2021-10-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_super_admin',
        ),
    ]
